ITD.WebApi/Controllers/MVC/ScreenController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using ITD.WebApi.Models;

namespace ITD.WebApi.Controllers
{
    public class ScreenController : Controller
    {
        private KeonCenterContext db = new KeonCenterContext();
        
        // GET: Screen
        public async Task<ActionResult> Index()
        {
            IEnumerable<ITD.WebApi.Models.CurrentTests> currentTests = await db.CurrentTests.OrderBy(p => p.TestCloses).ToListAsync();

            foreach (CurrentTests test in currentTests)
            {
                test.GetSections();
            }

            return View(currentTests);
        }

        [HttpGet]
        public async Task<PartialViewResult> Exams()
        {
            string[] sqlString = new string[] {
                "SELECT Value FROM  tlSettings WHERE Property = 'TestSubmission:StartTimeWeekday'",
                "SELECT Value FROM  tlSettings WHERE Property = 'TestSubmission:EndTimeWeekday'",
                "SELECT Value FROM  tlSettings WHERE Property = 'TestSubmission:StartTimeFriday'",
                "SELECT Value FROM  tlSettings WHERE Property = 'TestSubmission:EndTimeFriday'",
                "SELECT Value FROM  tlSettings WHERE Property = 'TestSubmission:StartTimeSaturday'",
                "SELECT Value FROM  tlSettings WHERE Property = 'TestSubmission:EndTimeSaturday'"};

            SqlDataArray times = new SqlDataArray();
            times.FillArrayValues(sqlString);

            ViewData["StartTimeWeekday"] = times.SqlArray[0];
            ViewData["EndTimeWeekday"] = times.SqlArray[1];
            ViewData["StartTimeFriday"] = times.SqlArray[2];
            ViewData["EndTimeFriday"] = times.SqlArray[3];
            ViewData["EndTimeSaturday"] = times.SqlArray[4];
            ViewData["EndTimeSaturday"] = times.SqlArray[5];
            
            IEnumerable<ITD.WebApi.Models.CurrentTests> model = await db.CurrentTests.OrderBy(p => p.TestCloses).ToListAsync();
            foreach (CurrentTests test in model)
            {
                test.GetSections();
            }
            return PartialView("_CurrentExams", model);
        }

        [HttpGet]
        public PartialViewResult Stats()
        {
            #region DateTime

            DateTime endOfWeek = DateTime.Today;

            do
            {
                endOfWeek = endOfWeek.AddDays(1);
            } while (endOfWeek.DayOfWeek != DayOfWeek.Saturday);

            #endregion

            #region SQL

            string[] sqlString = new string[] {
                //- Seats Available:
                "SELECT (SELECT Value FROM  tlSettings WHERE Property = 'AvailableSeats') - (SELECT COUNT(DISTINCT NID) FROM  vCurrent_Patrons)", 
                //- Tests Ending Today:
                "SELECT ISNULL(SUM(Students_Enrolled - Tests_Taken), 0) FROM tlTests WHERE Close_Date_Time BETWEEN GETDATE() AND (CONVERT(CHAR(10),GETDATE(),120) + ' 23:59:59') AND (dbo.tlTests.IsActive = 1)",
                //- Tests Ending this Week:
                "SELECT ISNULL(SUM(Students_Enrolled - Tests_Taken), 0) FROM dbo.tlTests WHERE Close_Date_Time BETWEEN GETDATE() AND '" + endOfWeek.ToShortDateString() + " 23:59:59'"};

            ModelState.Clear();

            SqlDataArray stats = new SqlDataArray();
            stats.FillArrayValues(sqlString);

            ViewData["SeatsAvailable"] = stats.SqlArray[0];
            ViewData["ClosingToday"] = stats.SqlArray[1];
            ViewData["ClosingWeek"] = stats.SqlArray[2];

            #endregion

            return PartialView("_CurrentStats");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ITD.WebApi/Views/Screen/Index.cshtml
@{
    ViewBag.Title = "Exams Screen";
    Layout = "~/Views/Shared/_Screen.cshtml";
}

@section Scripts {
    <script>
        $(function () {
            getExams();
            setInterval(getExams, 3000000); //<-- 50 min. refresh

            getStats();
            setInterval(getStats, 120000); //<-- 2 min. refresh
        });

        function getExams() {
            //GET: Exams List
            $.get('@Url.Action("Exams", "Screen")'
                ).done(function (data) {
                    $("#divExams").html(data).fadeIn('fast');
                });
        }

        function getStats() {
            //GET: Stat Counts
            $.get('@Url.Action("Stats", "Screen")'
                ).done(function (data) {
                    $("#divStats").html(data).fadeIn('fast');
                });
        }
</script>
}

<!-- Exam Listing
================================================== -->
<div class="carousel-container row">
    <div id="examCarousel" class="carousel slide" data-ride="carousel">
        <div id="divExams" class="carousel-inner" role="listbox"></div>
    </div>
</div><!-- /.carousel -->

<!-- Stat Counts
================================================== -->
<div id="divStats" class="stats-container"></div><!-- /.stats -->

ITD.WebApi/Views/Screen/_CurrentExams.cshtml
@model IEnumerable<ITD.WebApi.Models.CurrentTests>

<!-- Items -->
<div class="item active">
    <div class="carousel-caption">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="main-title">KEON TESTING CENTER</h1>
                <p>&nbsp;</p>
                <p class="operating-day"><span>@DateTime.Now.ToLongDateString()</span></p>

                @if (DateTime.Now.DayOfWeek != DayOfWeek.Friday || DateTime.Now.DayOfWeek != DayOfWeek.Saturday)
                {
                    <p class="operating-hrs">Hours: @ViewData["StartTimeWeekday"] <span>to</span> @ViewData["EndTimeWeekday"]</p>
                }
                else if (DateTime.Now.DayOfWeek == DayOfWeek.Friday)
                {
                    <p class="operating-hrs">Hours: @ViewData["StartTimeFriday"] <span>to</span> @ViewData["EndTimeFriday"]</p>
                }
                else if (DateTime.Now.DayOfWeek == DayOfWeek.Saturday)
                {
                    <p class="operating-hrs">Hours: @ViewData["EndTimeSaturday"]<span>to</span> @ViewData["EndTimeSaturday"]</p>
                }

                <p>&nbsp;</p>
            </div>
        </div>
    </div>
</div>

@{
    int testItem = 0;
    foreach (var item in Model)
    {
        <div class="item">
            <div class="carousel-caption">
                <div class="row">
                    <div class="col-lg-12">
                        <p class="course-num">
                            @Html.DisplayFor(modelItem => item.CoursePrefix)
                            @Html.DisplayFor(modelItem => item.CourseNumber)
                        </p>

                        <p class="course-title">
                            @Html.DisplayFor(modelItem => item.CourseTitle)
                        </p>

                        <p class="exam-title">
                            @Html.DisplayFor(modelItem => item.CourseTest)
                        </p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-6 text-left">
                        <br />
                        <p><strong><span class="text-grey">Closes: </span></strong> @Html.DisplayFor(modelItem => item.TestCloses)</p>
                        <p><strong><span class="text-grey">Completed: </span></strong> @Html.DisplayFor(modelItem => item.TestsTaken) of @Html.DisplayFor(modelItem => item.StudentsEnrolled)</p>
                    </div>

                    <div class="col-lg-6 text-right">
                        <p class="professor">@Html.DisplayFor(modelItem => item.Professor)</p>
                        <p class="course-section">Sections @item.strSections</p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-12 test-count">
                        @{testItem += 1;}
                        @testItem &nbsp; <em>of</em> &nbsp; @Model.Count()
                    </div>
                </div>

            </div>
        </div>
    }
}

<!-- Left and right controls -->
<a class="left carousel-control" href="#examCarousel" role="button" data-slide="prev">
    <span class="sr-only"></span>
</a>

<a class="right carousel-control" href="#examCarousel" role="button" data-slide="next">
    <span class="sr-only"></span>
</a>

ITD.WebApi/Views/Screen/_CurrentStats.cshtml
@model IEnumerable<string>

@helper formatCount(string seats)
{
    var count = Convert.ToInt32(seats);
    var color = "green";
    if (count < 20)
    {
        color = "red";
    }
    <span style="color:@color">@string.Format("{0}", count)</span>
}

<div class="row">
    <div class="col-lg-4 text-center"></div>
    <div class="col-lg-4 text-center"></div>
    <div class="col-lg-4 text-center"></div>
    <br />
</div>

<div class="row stat-row">
    <div class="col-lg-4 text-center">
        <h3>TESTS ENDING</h3>
        <h4>Today</h4>
        <p class="stat-count">@ViewData["ClosingToday"]</p>
    </div>
    <div class="col-lg-4 text-center">
        <h3>&nbsp;</h3>
        <h4>Seats Available</h4>
        <p class="stat-count">@formatCount(@ViewData["SeatsAvailable"].ToString())</p>
    </div>
    <div class="col-lg-4 text-center">
        <h3>TESTS REMAINING</h3>
        <h4>Week</h4>
        @if (DateTime.Now.DayOfWeek != DayOfWeek.Saturday)
        {  
            <p class="stat-count">@ViewData["ClosingWeek"]</p>
        }
    </div>
</div>

<div class="row">
    <div class="col-lg-12">
        <p>&nbsp;</p>
        <p class="text-center">Information is updated every 2 minutes. Last updated: <span id="current">@DateTime.Now.ToShortDateString() at @DateTime.Now.ToShortTimeString()</span></p>
    </div>
</div>